version: '3'
services:
    web:
        image: nginx:latest
        container_name: "compose-nginx"
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app_net
        privileged: true
        volumes:
            - ./www:/www
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./key:/key
            - ./log:/var/log/nginx/
        depends_on:
            - mysqldb
            - php

    php:
        build: ./phpbuild
        container_name: "compose-php"
        ports:
            - "9000:9000"
        privileged: true
        volumes:
            - ./www:/www
        networks:
            app_net:
                ipv4_address: 10.10.10.2

    mysqldb:
        image: mysql:5
        container_name: "compose-mysql"
        privileged: true
        volumes:
            - ./my.cnf:/etc/mysql/conf.d/my.cnf
            - ./dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            app_net:
                ipv4_address: 10.10.10.1
        environment:
            - MYSQL_HOST= 
            - MYSQL_ROOT_PASSWORD=password

networks:
    app_net:
        driver: bridge
        ipam:
            config:
                - subnet: 10.10.0.0/16


